Bump kotlin-reflect from 1.5.31 to 1.6.0 (#167)
Bumps [kotlin-reflect](https://github.com/JetBrains/kotlin) from 1.5.31 to 1.6.0.
e notes</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/releases">kotlin-reflect's releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.6.0-RC2</h2>
<h2><a href="https://kotlinlang.org/docs/install-eap-plugin.html">Learn how to install Kotlin 1.6.0-RC2 plugin</a> and <a href="https://kotlinlang.org/docs/configure-build-for-eap.html">how to configure build with 1.6.0-RC2</a></h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<h4>New Features</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43919"><code>KT-43919</code></a> Support loading Java annotations on base classes and implementing interfaces'  type arguments</li>
</ul>
<h4>Performance Improvements</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45185"><code>KT-45185</code></a> FIR2IR: get rid of IrBuiltIns usages</li>
</ul>
<h4>Fixes</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49477"><code>KT-49477</code></a> Has ran into recursion problem with two interdependant delegates</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49371"><code>KT-49371</code></a> JVM / IR: &quot;NoSuchMethodError&quot; with multiple inheritance</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49294"><code>KT-49294</code></a> Turning FlowCollector into 'fun interface' leads to AbstractMethodError</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-18282"><code>KT-18282</code></a> Companion object referencing it's own method during construction compiles successfully but fails at runtime with VerifyError</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-25289"><code>KT-25289</code></a> Prohibit access to class members in the super constructor call of its companion and nested object</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-32753"><code>KT-32753</code></a> Prohibit <a href="https://github.com/JvmField"><code>@​JvmField</code></a> on property in primary constructor that overrides interface property</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43433"><code>KT-43433</code></a> <code>Suspend conversion is disabled</code> message in cases where it is not supported and quickfix to update language version is suggested</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49209"><code>KT-49209</code></a> Default upper bound for type variables should be non-null</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-22562"><code>KT-22562</code></a> Deprecate calls to &quot;suspend&quot; named functions with single dangling lambda argument</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49335"><code>KT-49335</code></a> NPE in <code>RepeatedAnnotationLowering.wrapAnnotationEntriesInContainer</code> when using <code>@Repeatable</code> annotation from different file</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49322"><code>KT-49322</code></a> Postpone promoting warnings to errors for <code>ProperTypeInferenceConstraintsProcessing</code> feature</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49285"><code>KT-49285</code></a> Exception on nested builder inference calls</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49101"><code>KT-49101</code></a> IllegalArgumentException: ClassicTypeSystemContext couldn't handle: Captured(out Number)</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36399"><code>KT-36399</code></a> Gradually support TYPE_USE nullability annotations read from class-files</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-11454"><code>KT-11454</code></a> Load annotations on TYPE_USE/TYPE_PARAMETER positions from Java class-files</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-18768"><code>KT-18768</code></a> <code>@Notnull</code> annotation from Java does not work with varargs</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-24392"><code>KT-24392</code></a> Nullability of Java arrays is read incorrectly if <code>@Nullable</code> annotation has both targets TYPE_USE and VALUE_PARAMETER</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-48157"><code>KT-48157</code></a> FIR: incorrect resolve with built-in names in use</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46409"><code>KT-46409</code></a> FIR: erroneous resolve to qualifier instead of extension</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-44566"><code>KT-44566</code></a> <code>FirConflictsChecker</code> do not check for conflicting overloads across multiple files</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-37318"><code>KT-37318</code></a> FIR: Discuss treating flexible bounded constraints in inference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45989"><code>KT-45989</code></a> FIR: wrong callable reference type inferred</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46058"><code>KT-46058</code></a> [FIR] Remove state from some checkers</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45973"><code>KT-45973</code></a> FIR: wrong projection type inferred</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43083"><code>KT-43083</code></a> [FIR] False positive 'HIDDEN' on internal</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46727"><code>KT-46727</code></a> Report warning on contravariant usages of star projected argument from Java</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-40668"><code>KT-40668</code></a> FIR: Ambiguity on qualifier when having multiple different same-named objects in near scopes</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-37081"><code>KT-37081</code></a> [FIR] errors NO_ELSE_IN_WHEN and INCOMPATIBLE_TYPES absence</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-48162"><code>KT-48162</code></a> NON_VARARG_SPREAD isn't reported on *toTypedArray() call</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45118"><code>KT-45118</code></a> ClassCastException caused by parent and child class in if-else</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-47605"><code>KT-47605</code></a> Kotlin/Native: switch to LLD linker for MinGW targets</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-44436"><code>KT-44436</code></a> Support default not null annotations to enhance T into T!!</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-49190"><code>KT-49190</code></a> Increase stub versions</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md">kotlin-reflect's changelog</a>.</em></p>
<blockquote>
<h1>CHANGELOG</h1>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a href="https://github.com/JetBrains/kotlin/commits">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin:kotlin-reflect&package-manager=gradle&previous-version=1.5.31&new-version=1.6.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>

PR-URL: https://github.com/RBusarow/Gradle-Template/pull/167